// ledgerDummyData.js
export const GLDummyData = [
  /* ================= NORMAL RECORD ================= */
  {
    account: "500100",
    accountName: "Fuel Expense",
    vesselImo: "9387421",
    vesselName: "MV OCEAN STAR",
    accountingPeriod: "2024-06-01",
    documentNumber: "DOC-1001",
    accountingNumber: "ACC-77881",
    transactionDate: "2024-06-15",
    baseCurrency: "USD",
    baseAmount: 12500.75,
    foreignCurrency: "USD",
    foreignAmount: 12500.75,
    grossAmount: 12500.75,
    memo: "Fuel bunkering invoice June",
    transactionType: "Journal",
    aeReferencePO: "PO-45678",
    errorFlag: 0,
  },

  /* ================= ERROR RECORD (AE ERROR) ================= */
  {
    errorReason: "Invalid GL Account",
    vesselImo: "9412345",
    vesselName: "MV SEA HAWK",
    accountingPeriod: "2024-05-01",
    documentNumber: "DOC-1002",
    accountingNumber: "ACC-77882",
    transactionDate: "2024-05-20",
    baseCurrency: "USD",
    baseAmount: 8200.0,
    foreignCurrency: "USD",
    foreignAmount: 8200.0,
    memo: "Repair cost posting",
    transactionType: "Invoice",
    aeReferencePO: "PO-45999",
    errorFlag: 1,
  },

  /* ================= VSHIPS ERROR RECORD ================= */
  {
    errorReason: "Company ID mismatch",
    coyId: "VS001",
    voucherNo: "VCH-88991",
    voucherType: "JV",
    reference: "REF-3321",
    vesselName: "MV BLUE OCEAN",
    currency: "EUR",
    amountBase: 4500.25,
    createdDate: "2024-04-18",
    errorFlag: 1,
  },

  /* ================= VALIDATE API RECORD ================= */
  {
    extStatus: "Validated",
    extAccountingDate: "2024-06-30",
    extCurrencyCode: "USD",
    extUserJeSourceName: "INSW",
    extUserJeCategoryName: "GENERAL",
    extSegment1: "100",
    extSegment2: "SHIP01",
    extSegment3: "500100",
    extSegment4: "OPS",
    extSegment5: "PRJ01",
    extSegment6: "INT01",
    extSegment7: "FUT01",
    extEnteredDr: 5000.0,
    extEnteredCr: 0.0,
    extAccountedDr: 5000.0,
    extAccountedCr: 0.0,
    extReference1: "BATCH-001",
    extReference10: "Monthly validation",
    periodName: "JUN-24",
    errorFlag: 0,
  },

  /* ================= UPLOAD EXCEL RECORD ================= */
  {
    account: "600200",
    lineMemo: "Spare parts purchase",
    coyId: "VS002",
    claims: "NO",
    project: "PRJ02",
    docType: "INV",
    clientAccNo: "CL-7789",
    clientAccDesc: "Spare Parts",
    accountCode: "600200",
    voucherNo: "VCH-99811",
    voucherType: "INV",
    reference: "REF-9911",
    text: "Spare parts for engine",
    amountFunctional: 3200.5,
    currency: "USD",
    amountBase: 3200.5,
    detailedText: "Cylinder head replacement",
    delivery: "Completed",
    createdDate: "2024-03-10",
    comment: "Uploaded via Excel",
    ledgerDate: "2024-03-12",
    errorFlag: 0,
  },
   {
    account: "600200",
    lineMemo: "Spare parts purchase",
    coyId: "VS002",
    claims: "NO",
    project: "PRJ02",
    docType: "INV",
    clientAccNo: "CL-7789",
    clientAccDesc: "Spare Parts",
    accountCode: "600200",
    voucherNo: "VCH-99811",
    voucherType: "INV",
    reference: "REF-9911",
    text: "Spare parts for engine",
    amountFunctional: 3200.5,
    currency: "USD",
    amountBase: 3200.5,
    detailedText: "Cylinder head replacement",
    delivery: "Completed",
    createdDate: "2024-03-10",
    comment: "Uploaded via Excel",
    ledgerDate: "2024-03-12",
    errorFlag: 0,
  }, {
    account: "600200",
    lineMemo: "Spare parts purchase",
    coyId: "VS002",
    claims: "NO",
    project: "PRJ02",
    docType: "INV",
    clientAccNo: "CL-7789",
    clientAccDesc: "Spare Parts",
    accountCode: "600200",
    voucherNo: "VCH-99811",
    voucherType: "INV",
    reference: "REF-9911",
    text: "Spare parts for engine",
    amountFunctional: 3200.5,
    currency: "USD",
    amountBase: 3200.5,
    detailedText: "Cylinder head replacement",
    delivery: "Completed",
    createdDate: "2024-03-10",
    comment: "Uploaded via Excel",
    ledgerDate: "2024-03-12",
    errorFlag: 0,
  },
   {
    account: "600200",
    lineMemo: "Spare parts purchase",
    coyId: "VS002",
    claims: "NO",
    project: "PRJ02",
    docType: "INV",
    clientAccNo: "CL-7789",
    clientAccDesc: "Spare Parts",
    accountCode: "600200",
    voucherNo: "VCH-99811",
    voucherType: "INV",
    reference: "REF-9911",
    text: "Spare parts for engine",
    amountFunctional: 3200.5,
    currency: "USD",
    amountBase: 3200.5,
    detailedText: "Cylinder head replacement",
    delivery: "Completed",
    createdDate: "2024-03-10",
    comment: "Uploaded via Excel",
    ledgerDate: "2024-03-12",
    errorFlag: 0,
  },
   {
    account: "600200",
    lineMemo: "Spare parts purchase",
    coyId: "VS002",
    claims: "NO",
    project: "PRJ02",
    docType: "INV",
    clientAccNo: "CL-7789",
    clientAccDesc: "Spare Parts",
    accountCode: "600200",
    voucherNo: "VCH-99811",
    voucherType: "INV",
    reference: "REF-9911",
    text: "Spare parts for engine",
    amountFunctional: 3200.5,
    currency: "USD",
    amountBase: 3200.5,
    detailedText: "Cylinder head replacement",
    delivery: "Completed",
    createdDate: "2024-03-10",
    comment: "Uploaded via Excel",
    ledgerDate: "2024-03-12",
    errorFlag: 0,
  },
   {
    account: "600200",
    lineMemo: "Spare parts purchase",
    coyId: "VS002",
    claims: "NO",
    project: "PRJ02",
    docType: "INV",
    clientAccNo: "CL-7789",
    clientAccDesc: "Spare Parts",
    accountCode: "600200",
    voucherNo: "VCH-99811",
    voucherType: "INV",
    reference: "REF-9911",
    text: "Spare parts for engine",
    amountFunctional: 3200.5,
    currency: "USD",
    amountBase: 3200.5,
    detailedText: "Cylinder head replacement",
    delivery: "Completed",
    createdDate: "2024-03-10",
    comment: "Uploaded via Excel",
    ledgerDate: "2024-03-12",
    errorFlag: 0,
  },
   {
    account: "600200",
    lineMemo: "Spare parts purchase",
    coyId: "VS002",
    claims: "NO",
    project: "PRJ02",
    docType: "INV",
    clientAccNo: "CL-7789",
    clientAccDesc: "Spare Parts",
    accountCode: "600200",
    voucherNo: "VCH-99811",
    voucherType: "INV",
    reference: "REF-9911",
    text: "Spare parts for engine",
    amountFunctional: 3200.5,
    currency: "USD",
    amountBase: 3200.5,
    detailedText: "Cylinder head replacement",
    delivery: "Completed",
    createdDate: "2024-03-10",
    comment: "Uploaded via Excel",
    ledgerDate: "2024-03-12",
    errorFlag: 0,
  },
];
