// ledgerColumns.js
export const apiColumns = [
  /* ================= AE ERRORS ================= */
  {
    key: "errorReason",
    label: "Error Reason",
    sourceApi: "ae-errors",
    visible: true,
    type: "string",
  },
  {
    key: "vesselImo",
    label: "Vessel IMO",
    sourceApi: "ae-errors",
    visible: true,
    type: "string",
  },
  {
    key: "accountingPeriod",
    label: "Accounting Period",
    sourceApi: "ae-errors",
    visible: true,
    type: "date",
  },
  {
    key: "documentNumber",
    label: "Document Number",
    sourceApi: "ae-errors",
    visible: true,
    type: "string",
  },
  {
    key: "accountingNumber",
    label: "Accounting Number",
    sourceApi: "ae-errors",
    visible: true,
    type: "string",
  },
  {
    key: "transactionDate",
    label: "Transaction Date",
    sourceApi: "ae-errors",
    visible: true,
    type: "date",
  },
  {
    key: "baseCurrency",
    label: "Base Currency",
    sourceApi: "ae-errors",
    visible: true,
    type: "string",
  },
  {
    key: "baseAmount",
    label: "Base Amount",
    sourceApi: "ae-errors",
    visible: true,
    type: "currency",
  },
  {
    key: "foreignCurrency",
    label: "Foreign Currency",
    sourceApi: "ae-errors",
    visible: true,
    type: "string",
  },
  {
    key: "foreignAmount",
    label: "Foreign Amount",
    sourceApi: "ae-errors",
    visible: true,
    type: "currency",
  },
  {
    key: "memo",
    label: "Memo",
    sourceApi: "ae-errors",
    visible: true,
    type: "string",
  },
  {
    key: "transactionType",
    label: "Transaction Type",
    sourceApi: "ae-errors",
    visible: true,
    type: "string",
  },
  {
    key: "aeReferencePO",
    label: "AE Reference PO",
    sourceApi: "ae-errors",
    visible: true,
    type: "string",
  },

  /* ================= VSHIPS ERRORS ================= */
  {
    key: "errorReason",
    label: "Error Reason",
    sourceApi: "vships-errors",
    visible: true,
    type: "string",
  },
  {
    key: "coyId",
    label: "Company ID",
    sourceApi: "vships-errors",
    visible: true,
    type: "string",
  },
  {
    key: "voucherNo",
    label: "Voucher No",
    sourceApi: "vships-errors",
    visible: true,
    type: "string",
  },
  {
    key: "voucherType",
    label: "Voucher Type",
    sourceApi: "vships-errors",
    visible: true,
    type: "string",
  },
  {
    key: "reference",
    label: "Reference",
    sourceApi: "vships-errors",
    visible: true,
    type: "string",
  },
  {
    key: "vesselName",
    label: "Vessel Name",
    sourceApi: "vships-errors",
    visible: true,
    type: "string",
  },
  {
    key: "amountBase",
    label: "Amount Base",
    sourceApi: "vships-errors",
    visible: true,
    type: "currency",
  },
  {
    key: "currency",
    label: "Currency",
    sourceApi: "vships-errors",
    visible: true,
    type: "string",
  },
  {
    key: "createdDate",
    label: "Created Date",
    sourceApi: "vships-errors",
    visible: true,
    type: "date",
  },

  /* ================= GENERAL LEDGER ================= */
  {
    key: "account",
    label: "Account",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "string",
  },
  {
    key: "accountName",
    label: "Account Name",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "string",
  },
  {
    key: "vesselImo",
    label: "Vessel IMO",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "string",
  },
  {
    key: "accountingPeriod",
    label: "Accounting Period",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "date",
  },
  {
    key: "documentNumber",
    label: "Document Number",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "string",
  },
  {
    key: "transactionDate",
    label: "Transaction Date",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "date",
  },
  {
    key: "baseAmount",
    label: "Base Amount",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "currency",
  },
  {
    key: "grossAmount",
    label: "Gross Amount",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "currency",
  },
  {
    key: "memo",
    label: "Memo",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "string",
  },
  {
    key: "transactionType",
    label: "Transaction Type",
    sourceApi: "getGeneralLedger",
    visible: true,
    type: "string",
  },

  /* ================= VALIDATE ================= */
  {
    key: "extStatus",
    label: "Status",
    sourceApi: "validate",
    visible: true,
    type: "string",
  },
  {
    key: "errorFlag",
    label: "Error Flag",
    sourceApi: "validate",
    visible: true,
    type: "number",
  },
];
